[package]
name = "chdb-rust"
version = "1.0.0"
edition = "2024"
keywords = ["clickhouse", "chdb", "database", "embedded", "analytics"]

[dependencies]
thiserror = "2"

[build-dependencies]
bindgen = "0.72.1"

[dev-dependencies]
